spring:
  application:
    name: myapp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: yogesh@123
    url: jdbc://mysql:localhost:3306/db
    username: yogesh
  main:
    banner-mode: 'off'
