server:
  port: 9190
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: YT23june02@#
    url: jdbc:mysql://localhost:3306/thymeleaf_db
    username: root
  Jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

        
    